name: Cypress test
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Cypress.io
        uses: cypress-io/github-action@v9.5.2
        with:
          start: npx start
   
